name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pytest:
    name: Linux • Py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install package (dev extras)
        run: python -m pip install -e '.[dev]'

      - name: Show environment
        run: |
          python -V
          python -c "import sys, numpy, pandas, scipy; print('numpy', numpy.__version__); print('pandas', pandas.__version__); print('scipy', scipy.__version__)"

      - name: Run tests
        run: pytest -q
