name: Run Pytest with Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run tests with pytest
        run: pytest
