name: Ruff
on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # any supported version is fine

      - name: Install Ruff
        run: python -m pip install -U ruff

      - name: Lint (no fixes)
        run: ruff check --output-format=github .

      - name: Verify formatting
        run: ruff format --check .
